import EditProfileForm from '@/components/EditProfileForm';
import { Metadata } from 'next';
import { Container } from 'react-bootstrap';

export const metadata: Metadata = {
  title: 'Profile | Moyozon',
  description: 'Generated by create next app',
};

export default function ProfilePage() {
  return (
    <>
      <Container className="my-6">
        <h2 className="my-3">Edit Profile</h2>
        <EditProfileForm />
      </Container>
    </>
  );
}
