import SignupForm from '@/components/SignupForm';
import { Metadata } from 'next';
import React from 'react';
import { Container } from 'react-bootstrap';

export const metadata: Metadata = {
  title: 'Moyozon Signup',
  description: 'Generated by create next app',
};

export default function SignupPage() {
  return (
    <>
      <Container className="mt-5 max-w-[600px]">
        <h3 className="my-3 text-center">Sign Up</h3>
        <SignupForm />
      </Container>
    </>
  );
}
