import DeleteButton from '@/components/DeleteButton';
import { getError } from '@/utils/errorHandler';
import { getUserInfoFromCookies } from '@/utils/getItemsFromCookies';
import axios from 'axios';
import { Metadata } from 'next';
import Link from 'next/link';
import { Badge, Container } from 'react-bootstrap';

export const metadata: Metadata = {
  title: 'Users (Admin) | Moyozon',
  description: 'Generated by create next app',
};

export interface User {
  _id: string;
  name: string;
  email: string;
  password: string;
  isAdmin: boolean;
}

const userInfo = await getUserInfoFromCookies();
const fetchUsers = async (): Promise<User[]> => {
  try {
    const { data } = await axios.get(
      `${process.env.NEXT_PUBLIC_API_BASE_URL}/users`,
      {
        headers: { authorization: `Bearer ${userInfo?.token}` },
      }
    );
    return data;
  } catch (error) {
    console.error('Error fetching orders:', getError(error));
    return [];
  }
};

export default async function UserListPage() {
  const users = await fetchUsers();

  return (
    <>
      <Container className="my-6">
        <h2 className="my-3">Users</h2>
        <table className="table">
          <thead>
            <tr>
              <th>ID</th>
              <th>NAME</th>
              <th>EMAIL</th>
              <th>ACTIONS</th>
            </tr>
          </thead>
          <tbody>
            {users.map((user) => (
              <tr key={user._id}>
                <td>
                  {user._id}&nbsp;
                  {user.isAdmin && (
                    <Badge pill bg="success">
                      ADMIN
                    </Badge>
                  )}
                </td>
                <td>{user.name}</td>
                <td>{user.email}</td>
                <td>
                  <Link href={`/admin/user/${user._id}`}>Edit</Link> &nbsp;
                  <DeleteButton
                    type="user"
                    user={user}
                    token={userInfo.token}
                  />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </Container>
    </>
  );
}
