import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'react-toastify/dist/ReactToastify.css';
import NavigationBar from '@/components/NavigationBar';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700'], // Load only the required font weights
  variable: '--font-montserrat', // CSS variable for use in Tailwind
});

export const metadata: Metadata = {
  title: 'Moyozon - E-commerce Website',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [sidebarOpen, setSidebarOpen] = useState(false);

  return (
    <html lang="en">
      <body className={`${montserrat.variable}  bg-gray-100  min-h-screen`}>
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
