import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'react-toastify/dist/ReactToastify.css';
import NavigationBar from '@/components/NavigationBar';
import {
  getInitialCartFromCookies,
  getUserInfoFromCookies,
} from '@/utils/getItemsFromCookies';
import { StoreProvider } from '@/store/Store';
import { ToastContainer } from 'react-toastify';

const raleway = Raleway({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-raleway', // Optional: Add a CSS variable name
});

export const metadata: Metadata = {
  title: 'Moyozon - E-commerce Website',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialCart = await getInitialCartFromCookies();
  const userInfo = await getUserInfoFromCookies();

  return (
    <html lang="en" className={raleway.variable}>
      <body
        className={`${raleway.className} bg-gray-100  min-h-screen w-screen`}
      >
        <StoreProvider initialCart={initialCart} userInfo={userInfo}>
          {' '}
          <NavigationBar />
          {children}
          <ToastContainer position="bottom-center" limit={1} />
          <footer className="text-center mt-5">Moyo 2025</footer>
        </StoreProvider>
      </body>
    </html>
  );
}
