import AdminProductsList from '@/components/AdminProductsList';
import { Metadata } from 'next';
import { Container } from 'react-bootstrap';

export const metadata: Metadata = {
  title: 'All Products (Admin) | Moyozon',
  description: 'Generated by create next app',
};
export default async function ProductListPage() {
  return (
    <>
      <Container className="my-6">
        <AdminProductsList />
      </Container>
    </>
  );
}
