import CheckoutSteps from '@/components/CheckoutSteps';
import PaymentMethodForm from '@/components/PaymentMethodForm';
import { Metadata } from 'next';
import React from 'react';
import { Container } from 'react-bootstrap';

export const metadata: Metadata = {
  title: 'Payment Method | Moyozon',
  description: 'Generated by create next app',
};

export default function PaymentMethodPage() {
  return (
    <>
      <Container className="mt-5 max-w-[600px]">
        <CheckoutSteps step1 step2 step3></CheckoutSteps>
        <h2 className="my-3">Payment Method</h2>
        <PaymentMethodForm />
      </Container>
    </>
  );
}
