import CartSummary from '@/components/CartSummary';
import { Metadata } from 'next';
import { Container, Row } from 'react-bootstrap';

export const metadata: Metadata = {
  title: 'Cart | Moyozon',
  description: 'Generated by create next app',
};

const CartPage = () => {
  return (
    <>
      <Container className="mt-5">
        <h1>Shopping Cart</h1>
        <Row>
          <CartSummary />
        </Row>
      </Container>
    </>
  );
};

export default CartPage;
